spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
#    url: jdbc:postgresql://localhost:5432/waterstation
    url: jdbc:postgresql://172.31.151.129:54320/waterstation
    tomcat:
      max-active: 2048
      min-idle: 512
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 定时任务相关配置
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  web:
    resources:
      static-locations: file:/mnt/Waterstation/qrcode/
server:
  servlet:
    context-parameters:
      Xmx: 2g
  port: 8788
  ssl:
    enabled: true
    key-store: classpath:waterstation.hexishuzi.com.jks
    key-store-password: rilaesrj
    key-store-type: JKS

    # 微信支付配置 notifyUrl：微信支付异步回调地址
pay:
  appId: wx715a08a8d60a8595 #应用id
  apiKey: gwxkjvfewvfabvcrxgrawvgs924ceaxj #商户私钥key
  mchId: 1677661558 #商户id
  appSecret: 24f03b851b81a1225c43f17535886eb9 #小程序密钥
  notifyUrl: /weixin/callback #支付回调地址
#wxpay:
#  mch:
#    mchid:'商家id'
#    key:'支付key'
#  pay:
#    appid: wx123456789a439 #微信公众号appid
#    api_key: gwxkjvfewvfabvcrxgrawvgs924ceaxj #公众号设置的api密钥
#    mch_id: 1603596731 #微信商户平台 商户id



