spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
#    url: jdbc:postgresql://localhost:5432/waterstation
    url: jdbc:postgresql://172.31.151.129:54320/waterstation
    tomcat:
      max-active: 2048
      min-idle: 512
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-parameters:
      Xmx: 2g
  port: 8788
  ssl:
    enabled: true
    key-store: classpath:waterstation.hexishuzi.com.jks
    key-store-password: rilaesrj
    key-store-type: JKS


